### ISSUE TITLE
Update for new API version

### ISSUE THREAD

**Issue by bsakai2000** [AutomaticDoorControl/AutoDoorCtrl-iOS#48]
The new API has a new set of API calls, removing the /admin endpoints and standardizing format for the api endpoints and JSON names. All endpoints are now lowercase, with underscores between words. This is not necessarily an exhaustive list, and I can't test it so I can't write a PR, but the following are my best guesses at the changes required to work with the new API

https://github.com/AutomaticDoorControl/AutoDoorCtrl-iOS/blob/0568574832639853d287d57cba30eea5d6c91e0d/autodoorctrl/Model%20Classes/Networking/LoginAPI.swift#L15
This can be quickly patched by just changing the admin value to api/login

https://github.com/AutomaticDoorControl/AutoDoorCtrl-iOS/blob/f6a4c32481393baea6f56e9068fe2c457f196ef9/autodoorctrl/Model%20Classes/Networking/LoginAPI.swift#L30
Param should be `rcsid`

https://github.com/AutomaticDoorControl/AutoDoorCtrl-iOS/blob/f6a4c32481393baea6f56e9068fe2c457f196ef9/autodoorctrl/Model%20Classes/Networking/LoginAPI.swift#L70
Param should be `rcsid`

https://github.com/AutomaticDoorControl/AutoDoorCtrl-iOS/blob/f6a4c32481393baea6f56e9068fe2c457f196ef9/autodoorctrl/Model%20Classes/Networking/DoorsAPI.swift#L16-L17
Updated values are `get_doors` and `open_door`

https://github.com/AutomaticDoorControl/AutoDoorCtrl-iOS/blob/f6a4c32481393baea6f56e9068fe2c457f196ef9/autodoorctrl/Model%20Classes/Networking/ServicesAPI.swift#L16-L17
Updated values are `add_to_active` and `request_access`

https://github.com/AutomaticDoorControl/AutoDoorCtrl-iOS/blob/f6a4c32481393baea6f56e9068fe2c457f196ef9/autodoorctrl/Model%20Classes/Networking/ServicesAPI.swift#L35-L36
Updated values are `submit_complaint` and `get_complaints`

https://github.com/AutomaticDoorControl/AutoDoorCtrl-iOS/blob/f6a4c32481393baea6f56e9068fe2c457f196ef9/autodoorctrl/Model%20Classes/Networking/ServicesAPI.swift#L99
Updated values are `rcsid`

https://github.com/AutomaticDoorControl/AutoDoorCtrl-iOS/blob/f6a4c32481393baea6f56e9068fe2c457f196ef9/autodoorctrl/Model%20Classes/Networking/ServicesAPI.swift#L123
Updates values are `location` and `message`

Reference: https://github.com/AutomaticDoorControl/AutoDoorCtrlWebAPIPHP/blob/changeTokens/README.md

**Comment by ljw980105** [comment]
Need to handle the bug on the post complaint API call: read post status code instead of reading for the `{}` returned as a response
