### ISSUE TITLE
iOS Launch: Write Promotional Text & Description 

### ISSUE THREAD

**Issue by ljw980105** [AutomaticDoorControl/AutoDoorCtrl-iOS#52]
**Description**: A description of your app, detailing features and functionality. It will also be used for your Apple Watch app.

**Promotional text**: Promotional text lets you inform your App Store visitors of any current app features without requiring an updated submission. This text will appear above your description on the App Store for customers with devices running iOS 11 or later, and macOS 10.13 or later.

**Comment by bsakai2000** [comment]
I think we want to hit 3 things - App uses bluetooth (so users understand the permissions), App is a companion for existing blue-button hardware, and App makes things easier/safer. Here's a first draft that mostly hits those but I think it sounds clunky

Description Draft:
The Automatic Door Control app is designed to allow users of blue disability access buttons to remotely open doors without needing to physically touch the buttons. The app uses Bluetooth to connect to custom hardware inside of existing door openers to trigger the door open event. ADC is a simple way to add functionality to existing door opener mechanisms, while allowing users to open doors more
 efficiently. See more in our [video](pretendLink)

**Comment by bsakai2000** [comment]
And we don't need any promo text for submission 1 right?

**Comment by ljw980105** [comment]
Yes the promo text is optional. It's just a nice thing to have
